### ISSUE TITLE
PolarPipeline with curve Extension crushes 

### ISSUE THREAD

**Issue by RobertSchueler** [VFDannenberg/hrosailing#16]
Resolves in

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 999 and the array at index 2 has size 1

Minimal Example:

```
from hrosailing.pipelinecomponents import *
from hrosailing.pipeline import *

handler = NMEAFileHandler(
    sentences=["VHW", "MWV"],
    attributes=["Wind speed", "Wind angle", "Water speed knots"]
)

pp = PolarPipeline(
    handler=handler,
    extension=CurveExtension()
)
pp("src/nmea/running_example.nmea")
```

**Comment by VFDannenberg** [comment]
fixed in commit 47370311cab678c70ec582cafd7289c4c1b651a1
