### ISSUE TITLE
model functions 3d assume symmetry

### ISSUE THREAD

**Issue by RobertSchueler** [VFDannenberg/hrosailing#6]
The model functions only model half of the data appropriately.
I guess Stefan Simon assumed symmetry.

**Comment by VFDannenberg** [comment]
So what exactly are you proposing? Could you maybe go into more detail, as to why it is a problem and how it manifests?

**Comment by VFDannenberg** [comment]
Fixed with commit 8083f59885fb274b5bb087e355ff98c37d925e2a
